spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 80MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: ${PORT:8080}

resend:
  api-key: ${RESEND_API_KEY}
  from: ${RESEND_FROM:onboarding@resend.dev}

application:
  security:
    jwt:
      secretKey: ${JWT_SECRET}
      expiration: 86400000
