spring:

  datasource:
    url: jdbc:sqlserver://ROCHI-PC\MSSQLSERVER01:1433;databaseName=suby;encrypt=true;trustServerCertificate=true
    username: subyuser
    password: Suby123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rocioaramay@gmail.com
    password: "amei gbzy bxce mmon"

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

application:
  security:
    jwt:
      secretKey: suby_super_secret_key_suby_super_secret_key_2026
      expiration: 86400000